# --------------------------- #
#      User Configuration     #
# --------------------------- #

url: http://www.sprucestreetgamers.com
title: Spruce Street Gamers
subtitle: A sinister evil broods
author: Sean Laurent
